Repository grimme-lab/xtb, pull requests merged in 2020-08, with the labels that each got.

#318 Make CMake behave similar to meson
  CMakeLists.txt
  README.md
  cmake/CMakeLists.txt
  cmake/README.adoc
  meson/README.adoc
  meson_options.txt
Labels: build

#320 Use Windows path separators for Windows builds
  src/mctc/CMakeLists.txt
  src/mctc/meson.build
  src/mctc/systools.F90
Labels: build

#323 Read dipole moments for mopac interface calculations
  src/extern/mopac.f90
  src/type/dummycalc.f90
Labels: enhancement

#324 Update references in README
  README.md
  assets/references.bib
  src/xhelp.f90
Labels: documentation

#328 Release contraint on meson for build on OSX
  .github/workflows/fortran-build.yml
  .travis.yml
Labels: build

#327 Reestablish PGI support
  cmake/CMakeLists.txt
  src/api/calculator.f90
  src/eeq_model.f90
  src/hessian.F90
Labels: bug, build
