Repository grimme-lab/xtb, pull requests merged in 2020-06, with the labels that each got.

#241 Separate logic for MKL linking from static option
  meson/meson.build
  meson_options.txt
Labels: build

#256 Implement Analytical Linearized Poisson Boltzmann Model
  TESTSUITE/eeq_model.f90
  TESTSUITE/gfnff.f90
  src/gfnff/gfnff_eg.f90
  src/main/defaults.f90
  src/main/setup.f90
  src/prog/main.F90
  src/scc_core.f90
  src/scf_module.f90
  src/set_module.f90
  src/setparam.f90
  src/solv/gbobc.f90
  src/type/solvent.f90
Labels: enhancement

#258 Update metadynamics path finder
  .xtbrc
  src/bias_path.f90
  src/geoopt_driver.f90
  src/optimizer.f90
  src/prog/main.F90
  src/relaxation_engine.f90
  src/set_module.f90
  src/type/setvar.f90
Labels: enhancement

#259 New interaction kernel for solvation model
  TESTSUITE/eeq_model.f90
  src/main/setup.f90
  src/set_module.f90
  src/setparam.f90
  src/solv/CMakeLists.txt
  src/solv/gbobc.f90
  src/solv/kernel.f90
  src/solv/meson.build
Labels: enhancement

#261 Regression: Parallelisation error for xTB hessians
  TESTSUITE/gfn0.f90
  TESTSUITE/gfn1.f90
  TESTSUITE/gfn2.f90
  TESTSUITE/gfnff.f90
  TESTSUITE/peeq.f90
  src/api/calculator.f90
  src/api/interface.f90
  src/api/results.f90
  src/bias_path.f90
  src/dynamic.f90
  src/geoopt_driver.f90
  src/gfnff/calculator.f90
  src/gfnff/struc_converter.f90
  src/hessian.F90
  src/main/property.f90
  src/main/setup.f90
  src/mdoptim.f90
  src/modef.f90
  src/optimizer.f90
  src/prog/main.F90
  src/relaxation_engine.f90
  src/scan_driver.f90
  src/screening.f90
  src/single.f90
  src/type/CMakeLists.txt
  src/type/calculator.f90
  src/type/dummycalc.f90
  src/type/meson.build
  src/type/restart.f90
  src/xtb/calculator.f90
Labels: bug

#264 Setup CI build with Intel compilers
  .travis.yml
  meson.build
  meson/meson.build
Labels: build

#279 charptr is ignored in loadGFNXXTB_api
  src/api/calculator.f90
Labels: C-API

#282 Correct reading/writing of charge in CT files
  src/io/reader/ctfile.f90
  src/io/writer/ctfile.f90
  src/prog/main.F90
Labels: bug

#281 Add tcl Environment Module
  assets/meson.build
  assets/templates/env-module.tcl
Labels: build, enhancement

#283 Regression: Fix reference occupations for d-block in GFN2
  TESTSUITE/CMakeLists.txt
  TESTSUITE/gfn2.f90
  TESTSUITE/meson.build
  TESTSUITE/molstock.f90
  TESTSUITE/tests_peeq.f90
  src/xtb/gfn2.f90
Labels: bug

#285 Fix GBSA printout
  src/main/property.f90
  src/solv/kernel.f90
Labels: bug

#292 Adjust buildoptions for GCC
  TESTSUITE/gfn0.f90
  TESTSUITE/gfn1.f90
  TESTSUITE/gfn2.f90
  TESTSUITE/molstock.f90
  meson.build
  meson/README.adoc
  src/read_gfn_param.f90
Labels: build

#293 Allow to unset the solvation model in the API
  src/api/calculator.f90
Labels: C-API
