Repository grimme-lab/xtb, pull requests merged in 2020-09, with the labels that each got.

#337 Provide a workaround wrapper for PGI builds
  src/solv/CMakeLists.txt
  src/solv/input.F90
  src/solv/meson.build
Labels: bug, build

#339 Compatibility changes for solvation model
  README.md
  assets/references.bib
  man/xtb.1.adoc
  src/prog/main.F90
  src/set_module.f90
  src/xhelp.f90
Labels: documentation

#344 Fixup preprocessor directives in hessian
  .github/workflows/fortran-build.yml
  .travis.yml
  meson.build
  src/hessian.F90
Labels: build

#316 Fix crash in get_environment_variable()
  src/mctc/systools.F90
Labels: bug

#349 Remove check for __PGIC__ preprocessor in hessian
  src/hessian.F90
Labels: bug, build
