Repository grimme-lab/xtb, pull requests merged in 2022-02, with the labels that each got.

#572 Update author list in README and program header
  README.md
  src/xhelp.f90
Labels: documentation

#577 Document --oniom option
  man/xtb.1.adoc
  src/xhelp.f90
Labels: documentation

#587 Fix hessian calculations for single atoms
  src/eeq_model.f90
  src/hessian.F90
  src/printout.f90
  src/prog/main.F90
  src/scf_module.F90
Labels: bug

#584 Added C API option to call gradient calculations on point charges
  README.md
  include/xtb.h
  src/api/calculator.f90
  src/api/interface.f90
  src/api/results.f90
  src/type/data.f90
  src/xhelp.f90
  src/xtb/calculator.f90
  test/api/c_api_example.c
  test/api/meson.build
Labels: enhancement, C-API
