Repository grimme-lab/xtb, pull requests merged in 2024-09, with the labels that each got.

#1089 aISS update
  src/docking/param.f90
  src/docking/search_nci.f90
  src/iff/iff_prepare.f90
  src/prog/dock.f90
  test/unit/test_docking.f90
Labels: bug

#1004 implemented -bhess option in xtb thermo submodule
  .github/workflows/fortran-build.yml
  src/hessian.F90
  src/prog/thermo.f90
Labels: enhancement

#1102 Update README.md with hints for macOS
  README.md
Labels: documentation

#1105 Allocate set%ffnb dynamically.
  src/gfnff/gfnff_ini.f90
  src/set_module.f90
  src/setparam.f90
Labels: method: GFN-FF, refactor
