Repository grimme-lab/xtb, pull requests merged in 2025-03, with the labels that each got.

#1077 Add explanation for translation entropy constants
  src/main/property.F90
  src/mctc/convert.f90
  src/mctc/mctc_constants.f90
  src/thermo.f90
  test/unit/test_thermo.f90
Labels: documentation

#1229 Fix Fukui function for PTB and change spin-state assignment
  src/prog/main.F90
  src/vertical.f90
Labels: bug, method: PTB

#1237 Fix reduced mass calculation
  src/freq/io.f90
  src/hessian.F90
Labels: bug, driver: hessian
