Repository grimme-lab/xtb, pull requests merged in 2025-02, with the labels that each got.

#1165 Fix ubuntu-latest CI and introduce Arm validation
  .github/workflows/fortran-build.yml
Labels: Pipeline

#1133 Better support for finding custom lapack implementaion
  meson/meson.build
Labels: build

#1153 CEH gradients
  man/xtb.1.adoc
  src/prog/main.F90
  src/set_module.f90
  src/setparam.f90
  src/tblite/calculator.F90
  src/xhelp.f90
Labels: enhancement

#1179 Enable hyphen separated range of atoms to modify mass
  src/constrain_param.f90
Labels: enhancement

#1176 Fix isotope hessian
  src/prog/main.F90
Labels: bug, easy to fix

#1188 Clarify units of the Hessian matrix
  src/hessian.F90
Labels: documentation
