Repository grimme-lab/xtb, pull requests merged in 2025-04, with the labels that each got.

#1178 Speed-up hot path of GFN2 geometry optimization
  src/coulomb/klopmanohno.f90
  src/disp/dftd4.F90
  src/xtb/hamiltonian.f90
Labels: driver: optimization

#1260 Update stale_label.yml
  .github/workflows/stale_label.yml
Labels: Pipeline

#1268 Avoid infinite `mopac` loops
  src/extern/mopac.f90
Labels: bug
